### ISSUE TITLE
Bot returning .dream files with cat command, no response with ecat.

### ISSUE THREAD

**Issue by oblivion2k** [aeristhy/Random-Cat#5]
Bot starts correctly and joins the server, but appears to not be parsing `https://aws.random.cat/meow` responses properly.
prefix + cat returns an attached link to a cat.dream file. This link, when saved and renamed as cat.jpg, is a picture of a random cat from `https://aws.random.cat/meow`. Prefix + ecat returns nothing.

Unsure how to attach any helpful logs, as I can't find where logs would be created, if there are any.

**Comment by oblivion2k** [comment]
I did get some errors starting the bot with `node bot.js` instead of pm2. Shortly after the bot starts the console returns

`(node:13976) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'client' of undefined
    at new MessageEmbed (C:\Users\obliv\Desktop\Random-Cat\node_modules\discord.js\src\structures\MessageEmbed.js:13:60)
    at C:\Users\obliv\Desktop\Random-Cat\bot.js:22:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)`

prefix + cat returns no console errors, but prefix + ecat returns

`(node:13976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside
 of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate th
e node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api
/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections t
hat are not handled will terminate the Node.js process with a non-zero exit code.`

Interestingly, sending prefix + cat after running prefix + ecat returns two cat.dream files. It appears the initial attempt is cached, but fails to send, and then it successfully sends the cached result and the current request when prefix + cat is received.

**Comment by aeristhy** [comment]
I see, seems like Discord.js or Discord did some stuff, I'll update this when I get back home.

Sorry for the inconvenience

**Comment by aeristhy** [comment]
@oblivion2k So late update but I finally updated to version 1 and fixes

**Comment by oblivion2k** [comment]
Works perfectly now, thanks!
